# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/AweisMulla/XDMA_DDR/XDMA_DDR.srcs/sources_1/bd/XDMA_PS_DDR/ip/XDMA_PS_DDR_processing_system7_0_0/XDMA_PS_DDR_processing_system7_0_0.xci
# IP: The module: 'XDMA_PS_DDR_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AweisMulla/XDMA_DDR/XDMA_DDR.gen/sources_1/bd/XDMA_PS_DDR/ip/XDMA_PS_DDR_processing_system7_0_0/XDMA_PS_DDR_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_PS_DDR_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/AweisMulla/XDMA_DDR/XDMA_DDR.srcs/sources_1/bd/XDMA_PS_DDR/ip/XDMA_PS_DDR_processing_system7_0_0/XDMA_PS_DDR_processing_system7_0_0.xci
# IP: The module: 'XDMA_PS_DDR_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AweisMulla/XDMA_DDR/XDMA_DDR.gen/sources_1/bd/XDMA_PS_DDR/ip/XDMA_PS_DDR_processing_system7_0_0/XDMA_PS_DDR_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDMA_PS_DDR_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
